# Site info
site_name: PyCO2SYS
site_author: Matthew P. Humphreys
site_description: Marine carbonate system calculations in Python
copyright: Copyright &copy; 2020-2024 Matthew P. Humphreys (GNU GPLv3)

# Github repo info
repo_name: mvdh7/PyCO2SYS
repo_url: https://github.com/mvdh7/PyCO2SYS

# Navigation
nav:
  - Overview: index.md
  - How to use PyCO2SYS: howto.md
  - Switching from v1 to v2: v1_to_v2.md
  - Validation: validate.md
  - References: refs.md
  - Version history: versions.md

# Appearance
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: white
    accent: deep orange
  font:
    text: Noto Sans
    code: Noto Sans Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - tables
extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
