# Site info
site_name: PyCO2SYS
site_author: Matthew P. Humphreys
site_description: Marine carbonate system calculations in Python
site_url: https://pyco2sys.readthedocs.io/
copyright: Copyright &copy; 2020–2023 Matthew P. Humphreys (GNU GPLv3)

# Github repo info
repo_name: mvdh7/PyCO2SYS
repo_url: https://github.com/mvdh7/PyCO2SYS

# Navigation
nav:
  - Overview: index.md
  - How to use PyCO2SYS: co2sys_nd.md
  - Uncertainty propagation: uncertainty.md
  - Validation: validate.md
  - References: refs.md
  - Version history: versions.md
  - Alternative interfaces:
    - MATLAB-style CO2SYS: co2sys.md

# Appearance
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: white
    accent: deep orange
  font:
    text: Noto Sans
    code: Noto Sans Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
